### ISSUE TITLE
Doesn't not show up on map

### ISSUE THREAD

**Issue by duncosta** [Jaboticnik/Mafiavolta#1]
Hi, why doesn't it appear on the map ?

**Comment by Jaboticnik** [comment]
Hello. I didnt set to enable blips, because everyone can see where is mafia's house. If you want to add blip for the location, put this text in config at the start between mafia and AuthorizedWeapons, so put this one line before Authorized Weapons:

		Blip = {
			Pos     = { x = 425.130, y = -979.558, z = 30.711 },
			Sprite  = 60,
			Display = 4,
			Scale   = 1.2,
			Colour  = 37,
		},

---------------------------------------------------------------------------
Then open client.lua and paste this text at the bottom: 

  -- Create blips
  Citizen.CreateThread(function()
  
	  for k,v in pairs(Config.mafiaStations) do
		  local blip = AddBlipForCoord(v.Blip.Pos.x, v.Blip.Pos.y, v.Blip.Pos.z)
  
		  SetBlipSprite (blip, v.Blip.Sprite)
		  SetBlipDisplay(blip, v.Blip.Display)
		  SetBlipScale  (blip, v.Blip.Scale)
		  SetBlipColour (blip, v.Blip.Colour)
		  SetBlipAsShortRange(blip, true)
  
		  BeginTextCommandSetBlipName("STRING")
		  AddTextComponentString(('Mafia'))
		  EndTextCommandSetBlipName(blip)
	  end
  
  end)

**Comment by duncosta** [comment]
Thank you !
